import { createSlice } from '@reduxjs/toolkit';

const initialAuthObj = {
  token: '',
  isLoggedIn: false
};

const initialUserObj = {
  name: '',
  password: '',
  UID: '',
  membership: '',
  last_login: null,
  access_level: 0,
  designation: '',
  email: ''
};

const authSlice = createSlice({
  name: 'auth',
  initialState: initialAuthObj,
  reducers: {
    setToken: (state, action) => {
      state.token = action.payload;
      state.isLoggedIn = true;
    },
    clearToken: () => initialAuthObj
  }
});

const userSlice = createSlice({
  name: 'user',
  initialState: initialUserObj,
  reducers: {
    setUser: (state, action) => action.payload,
    clearUser: () => initialUserObj
  }
});

// Export the actions generated by createSlice
export const { setToken, clearToken } = authSlice.actions;
export const { setUser, clearUser } = userSlice.actions;

// Export the reducers to include in the store
export const authReducer = authSlice.reducer;
export const userReducer = userSlice.reducer;